defmodule RbacAppWeb.Router do
  use RbacAppWeb, :router

  import AshAdmin.Router
  admin_browser_pipeline(:browser)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {RbacAppWeb.Layouts, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    # Load current_user from session (generated by ash_authentication_phoenix)
    plug(RbacAppWeb.LiveUserAuth)
    plug(RbacAppWeb.Plugs.LoadActorRoles)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/auth" do
    pipe_through(:api)
    forward("/", RbacAppWeb.AuthPlug)
  end

  scope "/" do
    pipe_through(:browser)

    live("/", RbacAppWeb.DashboardLive, :index)
    live("/users", RbacAppWeb.UsersLive.Index, :index)
    live("/users/:id", RbacAppWeb.UsersLive.Show, :show)
    live("/roles", RbacAppWeb.RolesLive.Index, :index)

    # AshAdmin (lock it down via LiveSession on_mount)
    ash_admin(
      "/admin",
      AshAuthentication.Phoenix.LiveSession.opts(
        on_mount: [{RbacAppWeb.LiveUserAuth, :admin_only}]
      )
    )
  end

  # GraphQL endpoint (Absinthe via AshGraphql)
  scope "/gql" do
    pipe_through([:api])
    forward("/", Absinthe.Plug, schema: RbacAppWeb.Graphql.Schema)
  end
end

# defmodule RbacAppWeb.Endpoint do
#   use Phoenix.Endpoint, otp_app: :rbac_app

#   # The session will be stored in the cookie and signed,
#   # this means its contents can be read but not tampered with.
#   # Set :encryption_salt if you would also like to encrypt it.
#   @session_options [
#     store: :cookie,
#     key: "_rbac_app_key",
#     signing_salt: "cAukvcQh",
#     same_site: "Lax"
#   ]

#   socket "/live", Phoenix.LiveView.Socket,
#     websocket: [connect_info: [session: @session_options]],
#     longpoll: [connect_info: [session: @session_options]]

#   # Serve at "/" the static files from "priv/static" directory.
#   #
#   # When code reloading is disabled (e.g., in production),
#   # the `gzip` option is enabled to serve compressed
#   # static files generated by running `phx.digest`.
#   plug Plug.Static,
#     at: "/",
#     from: :rbac_app,
#     gzip: not code_reloading?,
#     only: RbacAppWeb.static_paths(),
#     raise_on_missing_only: code_reloading?

#   # Code reloading can be explicitly enabled under the
#   # :code_reloader configuration of your endpoint.
#   if code_reloading? do
#     socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
#     plug Phoenix.LiveReloader
#     plug Phoenix.CodeReloader
#     plug Phoenix.Ecto.CheckRepoStatus, otp_app: :rbac_app
#   end

#   plug Phoenix.LiveDashboard.RequestLogger,
#     param_key: "request_logger",
#     cookie_key: "request_logger"

#   plug Plug.RequestId
#   plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

#   plug Plug.Parsers,
#     parsers: [:urlencoded, :multipart, :json],
#     pass: ["*/*"],
#     json_decoder: Phoenix.json_library()

#   plug Plug.MethodOverride
#   plug Plug.Head
#   plug Plug.Session, @session_options
#   plug RbacAppWeb.Router
# end
